observation:
  fully_observable: false
  flatten: true

difficulties:
  easy:
    env_id: MERLIN-Easy-16x16-v0
    params:
      render_mode: rgb_array

  medium:
    env_id: MERLIN-Medium-16x16-v0
    params:
      render_mode: rgb_array

  hard:
    env_id: MERLIN-Hard-16x16-v0
    params:
      render_mode: rgb_array

  hardest:
    env_id: MERLIN-Hardest-16x16-v0
    params:
      render_mode: rgb_array
